- name: Update repositories cache
  ansible.builtin.apt:
    update_cache: yes

- name: Download OWASP ZAP
  ansible.builtin.get_url:
    url: "{{ zap_download_url }}"
    dest: "{{ zap_download_path }}"

- name: Run ZAP Proxy installation script
  shell: echo -ne '1 o \n \n \n \n \n \n \n \n \n 1\n 1\n 1\n y\n y\n y\n y\n y\n' | sudo sh "{{ zap_download_path }}"
